Improve termination scripts

diff --git a/roles/installer/files/pre-stop/termination-master b/roles/installer/files/pre-stop/termination-master
--- a/roles/installer/files/pre-stop/termination-master
+++ b/roles/installer/files/pre-stop/termination-master
@@ -5,25 +5,46 @@ source $(dirname "$0")/termination-env
 
 {
 
-log "hook has started\n"
+log "the hook has started: handler=\"%s\", heartbeat_file=\"%s\", bailout_file=\"%s\"" \
+  "$handler" \
+  "$heartbeat_file" \
+  "$bailout_file"
 
 set -o pipefail
-$(dirname "$0")/termination-handler 2>&1 | while IFS= read -r line; do
-  log "%s\n" "$line"
+$handler 2>&1 | while IFS= read -r line; do
+  # we check the files here and break early, but overall script termination
+  # happens later - as we need to distinguish between files detection and
+  # command failure, while bash doesn't offer a simple way to do this here
+  # inside the loop
+  [[ -f $bailout_file ]] && break
+  [[ -f $marker_file ]] && break
+
+  log "%s" "$line"
+  touch "$heartbeat_file"
 done
 ec=$?
 set +o pipefail
 
-if [[ $ec -ne 0 ]]; then
-  log "\"%s\" script has failed with \"%d\" exit code, failing the hook script too\n" \
-    "termination-handler" \
+# process various cases in specific order
+if [[ -f $bailout_file ]]; then
+  log "\"%s\" file has been detected, accepting bail out signal and failing the hook script" \
+    "$bailout_file"
+  exit 1
+elif [[ -f $marker_file ]]; then
+  log "done! \"%s\" file has been detected, assuming some other instance of the script has run to completion" \
+    "$marker_file"
+  exit 0
+elif [[ $ec -ne 0 ]]; then
+  log "\"%s\" command has failed with \"%d\" exit code, failing the hook script too" \
+    "$handler" \
     $ec
+  # signal others to bail out
+  touch "$bailout_file"
   exit $ec
+else
+  log "done! generating \"%s\" file allowing to proceed to termination" \
+    "$marker_file"
+  touch "$marker_file"
 fi
-
-log "done! generating \"%s\" file allowing to proceed to termination\n" \
-  "$marker_file"
-
-touch "$marker_file"
 
 } > "$stdout" 2> "$stderr"
diff --git a/roles/installer/files/pre-stop/termination-waiter b/roles/installer/files/pre-stop/termination-waiter
--- a/roles/installer/files/pre-stop/termination-waiter
+++ b/roles/installer/files/pre-stop/termination-waiter
@@ -5,29 +5,46 @@ source $(dirname "$0")/termination-env
 
 {
 
-log "hook has started\n"
-
-log "marker file to check: \"%s\"\n" \
-  "$marker_file"
-
-log "sleep between re-checks: \"%ss\"\n" \
-  "$recheck_sleep"
-
-log "report progress every: \"%ss\"\n" \
+log "the hook has started: marker_file=\"%s\", bailout_file=\"%s\", recheck_sleep=\"%d\", report_every=\"%d\"" \
+  "$marker_file" \
+  "$bailout_file" \
+  "$recheck_sleep" \
   "$report_every"
 
 n=0
-# TODO: check if master is still running, and fail otherwise - as master could
-# fail prematurely and then there is no sense to wait for the marker file
-# (subsequently, master needs to be updated to report its running status)
 while ! [[ -f $marker_file ]]; do
+  if [[ -f $bailout_file ]]; then
+    log "\"%s\" file has been detected, accepting bail out signal and failing the hook script" \
+      "$bailout_file"
+    exit 1
+  fi
+
   if [[ $(($n % $report_every)) -eq 0 ]]; then
-    log "waiting for marker file to be accessible\n"
+    log "waiting for marker file to be accessible"
   fi
   n=$(($n + 1))
   sleep $recheck_sleep
+
+  if ! [[ -f $heartbeat_file ]] \
+    || [[ $(( $(date +%s) - $(stat -c %Y "$heartbeat_file") )) -gt $recheck_sleep ]]; then
+    heartbeat_failed_count=$(( $heartbeat_failed_count + 1 ))
+    log "WARN: the heartbeat file hasn't been updated %d/%d iterations in a row" \
+      "$heartbeat_failed_count" \
+      "$heartbeat_failed_threshold"
+
+  else
+    heartbeat_failed_count=0
+  fi
+
+  if [[ $heartbeat_failed_count -ge $heartbeat_failed_threshold ]]; then
+    log "\"%s\" file hasn't been updated during the last %d iterations, assuming the master is not operating and failing the hook script" \
+      "$heartbeat_file" \
+      $heartbeat_failed_threshold
+    touch "$bailout_file"
+    exit 1
+  fi
 done
 
-log "marker file found, exiting to proceed to termination\n"
+log "marker file found, exiting to proceed to termination"
 
 } > "$stdout" 2> "$stderr"
