reformat heartbeat threshold logic

diff --git a/roles/installer/files/pre-stop/termination-env b/roles/installer/files/pre-stop/termination-env
--- a/roles/installer/files/pre-stop/termination-env
+++ b/roles/installer/files/pre-stop/termination-env
@@ -8,13 +8,12 @@ marker_file="${PRE_STOP_MARKER_FILE:-/var/lib/pre-stop/.termination_marker}"
 heartbeat_file="${PRE_STOP_HEARTBEAT_FILE:-/var/lib/pre-stop/.heartbeat}"
 
 # file which:
-# * `watcher`s create when they bail out because they didn't see the
-#   `heartbeat_file` to be updated within `$recheck_sleep *
-#   $heartbeat_failed_threshold`;
-# * `master` creates when its handler command fails;
+#   * `watcher`s create when they bail out because they didn't see the
+#   `heartbeat_file` to be updated within `$heartbeat_failed_threshold`;
+#   * `master` creates when its handler command fails;
 # when scripts see such file, they also give up
 bailout_file="${PRE_STOP_BAILOUT_FILE:-/var/lib/pre-stop/.bailout}"
-heartbeat_failed_threshold="${PRE_STOP_HEARTBEAT_FAILED_THRESHOLD:-60}"
+heartbeat_threshold="${PRE_STOP_HEARTBEAT_THRESHOLD:-60}"
 
 # where the scripts stdout/stderr are streamed
 stdout="${PRE_STOP_STDOUT:-/proc/1/fd/1}"
@@ -40,4 +39,27 @@ function parameters_sting {
   for param in "$@"; do
     printf "%s=\"%s\"\n" "$param" "${!param}"
   done | paste -s -d ' '
+}
+
+function check_bailout {
+  if [[ -f $bailout_file ]]; then
+    log "\"%s\" file has been detected, accepting bail out signal and failing the hook script" \
+      "$bailout_file"
+    exit 1
+  fi
+}
+
+function check_heartbeat {
+  if [[ -f $heartbeat_file ]]; then
+    delta=$(( $(date +%s) - $(stat -c %Y "$heartbeat_file") ))
+  else
+    delta=$(( $(date +%s) - $1 ))
+  fi
+
+  if [[ $delta -gt $heartbeat_threshold ]]; then
+    log "The heartbeat file hasn't been updated within the threshold of %ds, assuming the master is not operating and failing the hook script" \
+      $heartbeat_threshold
+    touch "$bailout_file"
+    exit 1
+  fi
 }
