Improve heartbeat/bailout logic

diff --git a/roles/installer/files/pre-stop/termination-waiter b/roles/installer/files/pre-stop/termination-waiter
--- a/roles/installer/files/pre-stop/termination-waiter
+++ b/roles/installer/files/pre-stop/termination-waiter
@@ -13,6 +13,7 @@ log "the hook has started: marker_file=\"%s\", bailout_file=\"%s\", recheck_slee
 
 n=0
 while ! [[ -f $marker_file ]]; do
+  # we check for `bailout_file` before sleep, to fail fast if the file is there
   if [[ -f $bailout_file ]]; then
     log "\"%s\" file has been detected, accepting bail out signal and failing the hook script" \
       "$bailout_file"
@@ -25,15 +26,26 @@ while ! [[ -f $marker_file ]]; do
   n=$(($n + 1))
   sleep $recheck_sleep
 
-  if ! [[ -f $heartbeat_file ]] \
-    || [[ $(( $(date +%s) - $(stat -c %Y "$heartbeat_file") )) -gt $recheck_sleep ]]; then
+  if [[ $n -ne 0 ]] && { \
+      ! [[ -f $heartbeat_file ]] \
+      || [[ $(( $(date +%s) - $(stat -c %Y "$heartbeat_file") )) -gt $recheck_sleep ]]; \
+    }; then
     heartbeat_failed_count=$(( $heartbeat_failed_count + 1 ))
-    log "WARN: the heartbeat file hasn't been updated %d/%d iterations in a row" \
-      "$heartbeat_failed_count" \
-      "$heartbeat_failed_threshold"
-
+    if [[ $(($n % $report_every)) -eq 0 ]]; then
+      log "WARN: the heartbeat file hasn't been updated %d/%d check iterations in a row" \
+        "$heartbeat_failed_count" \
+        "$heartbeat_failed_threshold"
+    fi
   else
     heartbeat_failed_count=0
+  fi
+
+  # we check again for `bailout_file` after sleep, as some other script might
+  # have created it already
+  if [[ -f $bailout_file ]]; then
+    log "\"%s\" file has been detected, accepting bail out signal and failing the hook script" \
+      "$bailout_file"
+    exit 1
   fi
 
   if [[ $heartbeat_failed_count -ge $heartbeat_failed_threshold ]]; then
